language: c
sudo: true
before_install:
  - sudo apt-get -y install libncurses-dev
script:
  - CFLAGS="-coverage -O0" make
  - CFLAGS="-coverage -O0" make test
  - find -name "*.c" -exec gcov \{\} \;
after_success:
  - bash <(curl -s https://codecov.io/bash)
